-- Replace RequestLog's plaintext client IP with a salted, day-rotating hash.
--
-- DESTRUCTIVE, DELIBERATELY: the "ip" column is DROPPED rather than renamed. The
-- addresses already stored there are plaintext personal data with no retention
-- policy behind them, and they are not even reliable — they come from the first
-- element of a caller-supplied X-Forwarded-For (see extractClientIp), so they are
-- a privacy liability that is not usable as evidence either way. Keeping them
-- under a new name would preserve exactly the problem this change exists to
-- remove, and would leave "ipHash" holding values that are not hashes.
--
-- Nothing reads the column: `grep -rn '\.ip\b' src/` finds no reader, only the
-- single write in src/lib/requestLog.ts. Dropping it is code-safe.
--
-- If those rows are wanted for a one-off investigation, snapshot them BEFORE
-- applying this migration — afterwards they are gone.
--
-- HOW TO APPLY IN PRODUCTION: `npx prisma db execute --url "$PROD_URL" --file
-- prisma/migrations/010_requestlog_ip_hash/migration.sql`, per
-- docs/agent-marketplace/HANDOFF.md §5. Do NOT run `prisma migrate deploy`
-- against production: the `0_init` baseline directory sorts *after* every
-- `0NN_`/`0NNN_` directory ('1' < '_'), so deploy would replay the whole history
-- and finish by trying to re-run the baseline, and HANDOFF.md §6 records that the
-- production `_prisma_migrations` table is not a reliable record of what is
-- already applied. Both statements below are idempotent, so a re-run is safe.
--
-- ORDERING vs the code deploy: `logRequest` catches its own write failure and
-- never throws, so either order only costs RequestLog rows, never a request (the
-- failures do show up as `requestLog failed:` lines). Applying
-- this before the new revision means the old code's `ip` write fails until the
-- deploy lands; applying it after means the new code's `ipHash` write fails until
-- the migration lands. Keep the gap short.

ALTER TABLE "RequestLog" DROP COLUMN IF EXISTS "ip";
ALTER TABLE "RequestLog" ADD COLUMN IF NOT EXISTS "ipHash" TEXT;
